### ISSUE TITLE
excel 导出图片 imagePath前面自动加了一串前缀，但是我这边拿到的url是另一台服务器的地址

### ISSUE THREAD

**Issue by archorfight** [zhangdaiscott/autopoi#17]
![image](https://user-images.githubusercontent.com/16200346/84725009-2f453a80-afbc-11ea-953c-fecc9f45e310.png)

该怎么搞？

**Comment by tygithub1** [comment]
更新依赖最新的代码
![image](https://user-images.githubusercontent.com/27989856/85289480-1c55cd00-b4ca-11ea-9e1e-4b00f5ad375d.png)
![image](https://user-images.githubusercontent.com/27989856/85289532-2e377000-b4ca-11ea-965b-2064306bd449.png)
